/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 * <p>
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 * <p>
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.bogdan.liferay.horseapp.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the HorseEntry service. Represents a row in the &quot;FOO_HorseEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.bogdan.liferay.horseapp.service.model.impl.HorseEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.bogdan.liferay.horseapp.service.model.impl.HorseEntryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @generated
 * @see HorseEntry
 */
@ProviderType
public interface HorseEntryModel extends BaseModel<HorseEntry> {

    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a horse entry model instance should use the {@link HorseEntry} interface instead.
     */

    /**
     * Returns the primary key of this horse entry.
     *
     * @return the primary key of this horse entry
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this horse entry.
     *
     * @param primaryKey the primary key of this horse entry
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the uuid of this horse entry.
     *
     * @return the uuid of this horse entry
     */
    @AutoEscape
    public String getUuid();

    /**
     * Sets the uuid of this horse entry.
     *
     * @param uuid the uuid of this horse entry
     */
    public void setUuid(String uuid);

    /**
     * Returns the entry ID of this horse entry.
     *
     * @return the entry ID of this horse entry
     */
    public long getEntryId();

    /**
     * Sets the entry ID of this horse entry.
     *
     * @param entryId the entry ID of this horse entry
     */
    public void setEntryId(long entryId);

    /**
     * Returns the model speed of this horse entry.
     *
     * @return the model speed of this horse entry
     */
    public int getModelSpeed();

    /**
     * Sets the model speed of this horse entry.
     *
     * @param modelSpeed the model speed of this horse entry
     */
    public void setModelSpeed(int modelSpeed);

}